# Python at DHSC {#py_at_dhsc}
The following are the DHSC [sensible defaults](#sensible_defaults) for Python:

## Version & IDE
Use Python 3 via [Jupyter Notebooks](https://jupyter.org/) or [VSCode](https://code.visualstudio.com/)

## Default Packages and Add Ins 

## General

* Use pandas for data analysis and reshaping
    * Use `loc` and `iloc` to index into data frames
* Use Altair for basic data visualisation
* Use Scikit Learn for machine learning
* Use SQLAlchemy and pandas for database interactions, rather than writing your own SQL

## Packages {#py_default_packages}

Recommended Packages: 

* Data Analysis
    * [pandas](https://pandas.pydata.org/)
* Database Interface
    * [SQLAlchemy](https://www.sqlalchemy.org/)
* Plotting
    * [Altair](https://altair-viz.github.io/)
    * [matplotlib](https://matplotlib.org/)
* Machine Learning
    * [sklearn](https://scikit-learn.org)

## Project Workflow {#py_projects}

Python has many different options, all supported by different IDEs and tools:

* Anaconda & Conda Projects - [Getting started with Conda](https://docs.conda.io/projects/conda/en/latest/user-guide/getting-started.html)

* Pycharm Projects - [Pycharm Projects](https://www.jetbrains.com/help/pycharm/project.html)

## Packaging Your Code {#py_packages}

Python - [Packaging Projects](https://packaging.python.org/tutorials/packaging-projects/)

## Managing Dependencies {#py_dependencies}

Virtual Environments [venv](https://docs.python.org/3/library/venv.html)

## Error Handling {#py_errorhandling}

In Python, an error can be a syntax error or an exception. Exceptions will crash your program as they are encountered. Fortunately, Python has a method for dealing with exception errors: the try-except block.  

The try-except block is used to catch and handle exceptions. Python executes code following the try statement as a “normal” part of the program.
The code that follows the except statement is the program’s response to any exceptions in the preceding try clause.  For example, 

```{python eval=FALSE, python.reticulate = FALSE}
try: 
    print(0/0)
except:
    print ("Cannot divide by O!" ) 
```
```
Cannot divide by O! 
```

It is also possible to write programs that handle selected exceptions (and this is generally considered good practice):

```{python eval=FALSE, python.reticulate = FALSE}
try:
    print(0/0) 
except ZeroDivisionError: 
    print ("Cannot divide by O!" ) 
Cannot divide by O! 
```
```
Cannot divide by O! 
```

And to handle different types of errors:
```{python eval=FALSE, python.reticulate = FALSE}
print(O/ j) 
    except ZeroDivisionError: 
print("Cannot divide by O!") 
    except NameError: 
print("Something else went wrong") 
```
```
Something else went wrong 
```

For more information see python documentation on [error handling](https://docs.python.org/3/tutorial/errors.html). 

## Unit Testing {#py_tests}
